[package]
name = "native_sdl"
version = "0.1.0"
authors = ["C63338"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
awbi_core = {path = "../core/", package = "core"}
